config:
  credentials: []
  project_repos:
    github.com/ARGOeu/argo-mon-library:
      branch: main
      repo: https://github.com/ARGOeu/argo-mon-library.git
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/pynblint_fix
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/ARGOeu/argo-mon-library git:
        commands:
        - /usr/bin/env sh .sqa/script.sage_grateful_badger.sh
        container: qc.acc_magenta_jubilant_platypus
  QC.Doc:
    repos:
      github.com/ARGOeu/argo-mon-library find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.seafoam_helpful_hamster.sh
        container: qc.doc_cyan_philosophical_tarantula
      github.com/ARGOeu/argo-mon-library git:
        commands:
        - /usr/bin/env sh .sqa/script.cardamom_plucky_kirin.sh
        container: qc.doc_pistachio_rustic_capybara
      github.com/ARGOeu/argo-mon-library markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.lilac_plucky_sloth.sh
        container: qc.doc_seafoam_harmonious_catfish
  QC.Lic:
    repos:
      github.com/ARGOeu/argo-mon-library licensee:
        commands:
        - /usr/bin/env sh .sqa/script.umber_calm_gazelle.sh
        container: qc.lic_isabelline_rustic_rhinoceros
  QC.Sec:
    repos:
      github.com/ARGOeu/argo-mon-library bandit:
        commands:
        - /usr/bin/env sh .sqa/script.peony_understanding_opossum.sh
        container: qc.sec_forest_studious_manatee
  QC.Sty:
    repos:
      github.com/ARGOeu/argo-mon-library flake8:
        commands:
        - /usr/bin/env sh .sqa/script.pumpkin_brilliant_badger.sh
        container: qc.sty_carmine_realistic_nighthawk
  QC.Uni:
    repos:
      github.com/ARGOeu/argo-mon-library pytest:
        commands:
        - /usr/bin/env sh .sqa/script.harlequin_confused_eagle.sh
        container: qc.uni_wave_fair_hornbill
  QC.Ver:
    repos:
      github.com/ARGOeu/argo-mon-library get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.jet_bright_ostrich.sh
        container: qc.ver_chocolate_diplomatic_piranha
timeout: 5400
