config:
  credentials: []
  project_repos:
    github.com/ARGOeu/argo-mon-library:
      branch: main
      repo: https://github.com/ARGOeu/argo-mon-library.git
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/ARGOeu/argo-mon-library git:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-lavender-akbash.sh
        container: qc.acc_skimpy-russet-drever
  QC.Doc:
    repos:
      github.com/ARGOeu/argo-mon-library find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-beige-swan.sh
        container: qc.doc_craggy-apricot-lemur
      github.com/ARGOeu/argo-mon-library git:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-emerald-vole.sh
        container: qc.doc_slaphappy-copper-quokka
      github.com/ARGOeu/argo-mon-library markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-green-lionfish.sh
        container: qc.doc_bumpy-myrtle-panda
  QC.Lic:
    repos:
      github.com/ARGOeu/argo-mon-library licensee:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-rose-hornet.sh
        container: qc.lic_gimpy-chestnut-liger
  QC.Sec:
    repos:
      github.com/ARGOeu/argo-mon-library bandit:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-wheat-wolf.sh
        container: qc.sec_clammy-buff-yak
  QC.Sty:
    repos:
      github.com/ARGOeu/argo-mon-library flake8:
        commands:
        - /usr/bin/env sh .sqa/script.surly-buff-chin.sh
        container: qc.sty_lousy-silver-wolverine
  QC.Uni:
    repos:
      github.com/ARGOeu/argo-mon-library pytest:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-crimson-rat.sh
        container: qc.uni_shaky-vermilion-paradise
  QC.Ver:
    repos:
      github.com/ARGOeu/argo-mon-library get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.messy-amber-ibis.sh
        container: qc.ver_silly-gamboge-spitz
timeout: 5400
