config:
  credentials: []
  project_repos:
    github.com/ARGOeu/argo-mon-library:
      branch: main
      repo: https://github.com/ARGOeu/argo-mon-library.git
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/ARGOeu/argo-mon-library git:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-cerulean-reindeer.sh
        container: qc.acc_pokey-aquamarine-mole
  QC.Doc:
    repos:
      github.com/ARGOeu/argo-mon-library find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-plum-wolfhound.sh
        container: qc.doc_greasy-azure-booby
      github.com/ARGOeu/argo-mon-library git:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-khaki-mandrill.sh
        container: qc.doc_squirrely-crimson-zebra
      github.com/ARGOeu/argo-mon-library markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-coral-toucan.sh
        container: qc.doc_nippy-brass-discus
  QC.Lic:
    repos:
      github.com/ARGOeu/argo-mon-library licensee:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-amethyst-whale.sh
        container: qc.lic_clammy-brown-wolf
  QC.Sec:
    repos:
      github.com/ARGOeu/argo-mon-library bandit:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-alizarin-horse.sh
        container: qc.sec_bumpy-copper-salamander
  QC.Sty:
    repos:
      github.com/ARGOeu/argo-mon-library flake8:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-plum-macaw.sh
        container: qc.sty_boozy-charcoal-dolphin
  QC.Uni:
    repos:
      github.com/ARGOeu/argo-mon-library pytest:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-maroon-toucan.sh
        container: qc.uni_silly-lavender-horse
  QC.Ver:
    repos:
      github.com/ARGOeu/argo-mon-library get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-tan-lemming.sh
        container: qc.ver_lumpy-persimmon-scorpion
timeout: 5400
